advanced/frontend/models/CategoryForm.php
<?php

namespace frontend\models;

use yii\base\Model;


class CategoryForm extends Model{

  public $perPage;
  public $sortBy;
  public $viewPage = '_categoryGrid';

  public function rules()
  {
    return [
      [['perPage', 'sortBy', 'viewPage'], 'required']
    ];
  }

  public function attributeLabels()
  {
    return [
      'perPage' => 'Отображать по:',
      'sortBy' => 'Сортировка по',
      'viewPage' => 'Вид',

    ];
  }

}

advanced/frontend/controllers/CartController.php
<?php

namespace frontend\controllers;

use frontend\models\ActiveRecord\Product;
use frontend\models\ActiveRecord\Cart;
use frontend\models\ProductForm;
use Yii;
use yii\helpers\Url;
use frontend\models\ActiveRecord\DiscountCode;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use frontend\models\CartForm;
use yii\helpers\VarDumper;
use yii2mod\comments\models\CommentModel;


/**
 * Class CartController
 * @package frontend\controllers
 */
class CartController extends MyController
{

  public $layout = 'main';

  /**
   * @var null|static
   */
  protected $_coupon;

  /**
   * @param string $id
   * @param \yii\base\Module $module
   * @param array $config
   */
  public function __construct($id, $module, $config = [])
  {
    $promoCode = Yii::$app->session->get('promocode');
    $code = DiscountCode::findOne(['str_code' => $promoCode]);
    /* @var $code \frontend\models\ActiveRecord\DiscountCode*/
    if($code){
      if($code->isActive())
        $this->_coupon = $code;
    }

    parent::__construct($id, $module, $config); // TODO: Change the autogenerated stub
  }

  /**
   * @return array
   */
  public function behaviors()
  {
    return [
      'verbs' => [
        'class' => VerbFilter::className(),
        'actions' => [
          'index'  => ['get'],
          'add' => ['post'],
          'update' => ['post'],
          'delete' => ['get' ,'post', 'delete'],
          'checkout' => ['post'],
        ],
      ],
    ];
  }

  /**
   * @return string
   */
  public function actionIndex()
  {
    $model = new Cart();
    $cartForm = new CartForm();

    if(!empty(Yii::$app->cart->items)){
      $items = $model->prepareItems(Yii::$app->cart->items, $this->_coupon);
    }else{
      Yii::$app->session->setFlash('error', 'Ваша корзина пуста!');
      $items = [];
    }
    //VarDumper::dump($items, 20, 1);
    return $this->render('index',['items' => $items, 'promocode' => $this->_coupon, 'model' => $cartForm]);
  }

  /**
   * @param $id
   */
  public function actionAdd()
  {
    $session = Yii::$app->session;
    $post = Yii::$app->request->post();

    $productModel = new Product(['scenario' => 'addToCart']);
    $productForm = new ProductForm();
    $attributesModel = new Product();

    $options = $attributesModel->prepareOptions($post['product_id']);

    $productForm->attachOptionsRules($options);
    $productForm->load($post);
    $productModel->product_id = $post['product_id'];

    if ($productModel->validate() && $productForm->validate()) {
      $cartModel = new Cart();
      $options = isset($post[basename($productForm::className())]) ? $post[basename($productForm::className())] : [];
      $item = $cartModel->addToCart(session_id(), $post['product_id'], $options );

      $session->setFlash('success', '"' . $item['name'] . '"'. ' - успешно добавлен в корзину!');
    }else{
      $session->setFlash('error', $productForm->getFirstErrors());
    }
    $this->redirect($_SERVER['HTTP_REFERER']);
  }

  /**
   * @param $id
   */
  public function actionDelete($id){
    $cartModel = new Cart();
    $cartModel->deleteFromCart(session_id(), $id);

    //Обновить данные в компоненте на основании сессии
    Yii::$app->cart->init();
    $data = $cartModel->prepareItems(Yii::$app->cart->items, $this->_coupon);

    echo json_encode($data);
  }

  /**
   * Обновить по ajax товары в корзине
   */
  public function actionUpdate()
  {
    $cartModel = new Cart();
    $post = Yii::$app->request->post();
    $cartModel->updateCart(session_id(), $post['cart']);

    $data = $cartModel->prepareItems(ArrayHelper::map($post['cart'], 'id', 'qty'), $this->_coupon);

    echo json_encode($data);
  }

  /**
   * Применить купон к товарам в корзине
   * Если в базе есть активный промокод, добавляется в сессию.
   * Если нет, добавляется flash сообщение об ощибке.
   */
  public function actionDiscount()
  {
    $post = Yii::$app->request->post();
    $session = Yii::$app->session;

    $code = DiscountCode::findOne(['str_code' => $post['code']]);
    /* @var $code \frontend\models\ActiveRecord\DiscountCode*/
    if($code) {
      if ($code->isActive())
        $session->set('promocode', $code->str_code);
      else{
        $session->remove('promocode');
        $session->setFlash('error', 'Данный купон более не действителен');
      }
    }
    $this->redirect('index');
  }

  public function actionCheckout()
  {

    $cartForm = new CartForm();
    $post = Yii::$app->request->post();
    $cartModel = new Cart();
    $items = $cartModel->prepareItems(Yii::$app->cart->items);
    if(empty($items))
      return $this->redirect(['category/category']);

    if($cartForm->load($post) && $cartForm->validate()){
      $order_id = $cartModel->saveOrder($post[basename(CartForm::className())], $items);
      $orderFields = $post[basename(CartForm::className())];
      $cartModel->prepareOrderFields($orderFields);

      return $this->render('checkout', [
        'items' => $items,
        'orderFields' => $orderFields,
        'order_id' => $order_id
      ]);
    }
    else{
      Yii::$app->session->setFlash('error', $cartForm->getFirstErrors());
      return $this->render('index',['items' => $items, 'promocode' => $this->_coupon, 'model' => $cartForm]);
    }
  }

  public function actionTest()
  {
    $commentModel = new CommentModel(['id' => 2]);
    return $this->render('comment', [
        'model' => $commentModel,
    ]);
  }
}

advanced/frontend/controllers/CategoryController.php
<?php

namespace frontend\controllers;

use frontend\models\ActiveRecord\CategoryDescription;
use frontend\models\ActiveRecord\Module;
use frontend\models\ActiveRecord\SeoTemplates;
use frontend\models\ActiveRecord\Category;
use frontend\models\ActiveRecord\Product;

use frontend\models\CategoryForm;
use yii\data\ActiveDataProvider;
use yii\data\Sort;
use frontend\components\MySort;
use yii\db\Query;
use yii\helpers\VarDumper;
use yii\helpers\ArrayHelper;
use yii2mod\comments\models\CommentModel;
use frontend\models\ProductForm;
use app\modules\Filter\components\FilterBehavior;
use yii\web\Controller;
use yii\data\ArrayDataProvider;
use Yii;

class CategoryController extends MyController
{
  public function __construct($id, $module, $config = [])
  {
    if(!Yii::$app->session->isActive)
      Yii::$app->session->open();
    parent::__construct($id, $module, $config);
  }

  public function behaviors()
  {
    return [];
  }

  public function actionCategory($id)
  {
    $model = new CategoryForm();
    $request = Yii::$app->request;
    $params = $request->getQueryParams();

    if ($request->isPost && $model->load($request->post()))
    {
      Yii::$app->session->set('perPage', $model->perPage);
    }
    elseif($request->isGet)
    {
      $model->perPage = $params['per-page'] ? $params['per-page'] : $model->perPage;
      Yii::$app->session->set('perPage', $model->perPage);
    }
    else{
      $model->perPage = Yii::$app->session->get('perPage');
    }

    $sort = new MySort([
      'attributes' => [
        'productName'=>[
          'asc' => ['product_description.Name' => SORT_ASC],
          'desc' => ['product_description.Name' => SORT_DESC],
          'default' => SORT_DESC,
          'label' => 'Имя',
        ],
        'price'=>[
          'asc' => ['price' => SORT_ASC],
          'desc' => ['price' => SORT_DESC],
          'default' => SORT_DESC,
          'label' => 'Цена',
        ],
      ],
      'enableMultiSort' => true
    ]);

    $provider = new ActiveDataProvider([
      'query' => Product::find()
        ->joinwith('productAttributes.attributeInfo.attributeDescription')
        ->joinwith('productDescription')
        ->with('productStickers.stickerDescription')
        ->with('productComments')
        ->joinWith('productCategories')
        ->where(['category_id' => $id])
        ->orderBy($sort->orders),
      'pagination' => [
        'pageSize' => $model->perPage ? $model->perPage : 20 ,
      ],
    ]);

    $moduleModel = new Module();
    $modules = $moduleModel->prepareModules('category/category');

    $categoryModel = new Category();

    return $this->render('category', [
      'provider' => $provider,
      'model' => $model,
      'sort' => $sort,
      'modules' => $modules,
      'breadcrumbs' => $categoryModel->prepareBreadcrumbs($id),
      'h1' => CategoryDescription::findOne(['category_id' => $id])->name
    ]);
  }

  public function actionProduct($id)
  {
    $attributesModel = new Product();
    $product = Product::findOne($id);

    $commentModel = new CommentModel(['id' => $id]);
    $attributes = $attributesModel->prepareAttributes($id);
    $options = $attributesModel->prepareOptions($id);

    $productForm = new ProductForm();
    $productForm->attachOptionsRules($options);
    /*
     * Last Viewed
     * */
    $lastViewed = Yii::$app->session->get('lastViewed');
    $lastViewed = (array)json_decode($lastViewed);
    $lastViewed[] = $id;
    Yii::$app->session->set('lastViewed', json_encode(array_values(array_unique((array)$lastViewed))));
    $seoModel = new SeoTemplates();

    //TODO:: Организовать в  behavior метатеги

    $metaTags = $seoModel->getReadyTemplates('product', $id);
    $moduleModel = new Module();
    $modules = $moduleModel->prepareModules('category/product');

    return $this->render('product', [
      'model' => $product,
      'attributes' => $attributes,
      'comment' => $commentModel,
      'options' => $options,
      'productForm' => $productForm,
      'modules' => $modules,
      'metaTags' => $metaTags

    ]);
  }
  public function actionSearch($q = '')
  {
    $model = new CategoryForm();
    $request = Yii::$app->request;
    $params = $request->getQueryParams();

    if ($request->isPost && $model->load($request->post()))
    {
      Yii::$app->session->set('perPage', $model->perPage);
    }
    elseif($request->isGet)
    {
      $model->perPage = $params['per-page'] ? $params['per-page'] : $model->perPage;
      Yii::$app->session->set('perPage', $model->perPage);
    }
    else{
      $model->perPage = Yii::$app->session->get('perPage');
    }

    /** @var \himiklab\yii2\search\Search $search */
    $search = Yii::$app->search;
    $searchData = $search->find($q); // Search by full index.
    //$searchData = $search->find($q, ['model' => 'ProductDescription']); // Search by index provided only by model `page`.

    $dataProvider = new ArrayDataProvider([
      'allModels' => $searchData['results'],
      'pagination' => ['pageSize' => 10],
    ]);

    $productIds = (new Category())->getSearchedIds($searchData['results']);

    $sort = new MySort([
      'attributes' => [
        'productName'=>[
          'asc' => ['product_description.Name' => SORT_ASC],
          'desc' => ['product_description.Name' => SORT_DESC],
          'default' => SORT_DESC,
          'label' => 'Имя',
        ],
        'price'=>[
          'asc' => ['price' => SORT_ASC],
          'desc' => ['price' => SORT_DESC],
          'default' => SORT_DESC,
          'label' => 'Цена',
        ],
      ],
      'enableMultiSort' => true
    ]);

    $provider = new ActiveDataProvider([
      'query' => Product::find()
        ->joinwith('productAttributes.attributeInfo.attributeDescription')
        ->joinwith('productDescription')
        ->with('productStickers.stickerDescription')
        ->with('productComments')
        ->joinWith('productCategories')
        ->where(['product.product_id' => $productIds])
        ->orderBy($sort->orders),
      'pagination' => [
        'pageSize' => 20 ,
      ],
    ]);

    $moduleModel = new Module();
    $modules = $moduleModel->prepareModules('category/search');

    return $this->render('found', [
      'provider' => $provider,
      'model' => $model,
      'sort' => $sort,
      'modules' => $modules,
      'query' => $searchData['query']
    ]);


  }

}

advanced/frontend/views/category/_product-options.php
<?
/* @var yii\base\Model $optionsForm Модель валидации формы опций */
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\jui\DatePicker;


  foreach ($options as  $option) {
    if($option['type'] == 'select'){
      echo $form
        ->field($optionsForm, 'option_' . $option['product_option_id'])
        ->dropDownList(ArrayHelper::map($option['product_option_value'], 'product_option_value_id', 'name'), ['prompt' => '--Выберите--'])
        ->label($option['name']);
    }elseif($option['type'] == 'radio'){
      echo $form
        ->field($optionsForm, 'option_' . $option['product_option_id'])
        ->radioList(ArrayHelper::map($option['product_option_value'], 'product_option_value_id', 'name'))
        ->label($option['name']);
    }elseif($option['type'] == 'checkbox'){
      echo $form
        ->field($optionsForm, 'option_' . $option['product_option_id'])
        ->checkboxList(ArrayHelper::map($option['product_option_value'], 'product_option_value_id', 'name'))
        ->label($option['name']);
    }elseif($option['type'] == 'datetime'){
      echo $form->field($optionsForm, 'option_' . $option['product_option_id'])->widget(DatePicker::classname(), [
        'dateFormat' => 'yyyy-MM-dd',
      ])->label($option['name']);
    }
  }
?>

advanced/frontend/views/category/category.php
<?php
/* @var $sort  */
/* @var $provider  */

use yii\widgets\Menu;
use yii\widgets\ListView;
use yii\widgets\LinkSorter;
use frontend\components\DropSort;
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\web\View;
use yii\helpers\Url;

foreach ($breadcrumbs as  $one) {
  $this->params['breadcrumbs'][] = $one;
}
//$this->params['breadcrumbs'][] = $h1;
?>

<h1><?=$h1?></h1>

<?php
\yii\widgets\Pjax::begin();

echo \common\widgets\Alert::widget();

$form = ActiveForm::begin([
  'id'=> 'sorter-form',
  'options'=>[
    'data-pjax' => '1'
  ]
]);
?>

<div class="display" data-toggle="buttons-radio">
  <span>Вид</span>
<?=Html::Submitbutton('<i class="fa fa-th-large"></i>',
  [
    'name' => 'ProductForm[viewPage]',
    'value' => '_categoryGrid',
    'class' => $model->viewPage == '_categoryGrid' ? 'active' : ''
  ])
?>
<?=Html::Submitbutton('<i class="fa fa-th-list"></i>',
  [
    'name' => 'CategoryForm[viewPage]',
    'value' => '_categoryList',
    'class' => $model->viewPage == '_categoryList' ? 'active' : ''
  ])
?>
</div>

<?
echo DropSort::widget([
  'sort' => $sort,
  'attributes' => [
    'productName'=>[
      'label'=>'Имя'
    ],
    'price'=>[
      'label'=>'Цена'
    ],
  ],
  'options' =>[
    'class' => 'form-control',
    'id' => 'DDL',
    'onchange' => 'window.location = $("#DDL").val();',
  ],
  'DDL' =>[
    'labelSelect' => 'Сортировать по'
  ]
]);

echo $form->field($model, 'perPage')->dropDownList([
  '20'=>"20",
  '40'=>"40",
  '60'=>'60',
  '80'=>'80',
  '100'=>'100',
],
[
  'id'=>'filterDrop',
  'onchange' => '$("#sorter-form").submit()'
]);
ActiveForm::end();

echo ListView::widget([
  'dataProvider' => $provider,
  'itemView' => 'ListView/'. $model->viewPage,
  'layout' => '{items}{summary}{pager}',
  'pager' => [
    'options' => ['class' => 'bootstrap-styles pagination center-pag']
  ],
]);?>


<?\yii\widgets\Pjax::end();?>

  <!--Top block-->
<? $this->beginBlock('top'); ?>
<?
if(isset($modules['content_top']))
  foreach($modules['content_top'] as $module){
    echo $module;
  }
?>
<? $this->endBlock();?>

  <!--Left block-->
<? $this->beginBlock('left'); ?>
<?
if(isset($modules['column_left']))
  foreach($modules['column_left'] as $module){
    echo $module;
  }
?>
<? $this->endBlock();?>

  <!--Right block-->
<? $this->beginBlock('right'); ?>
<?
if(isset($modules['column_right']))
  foreach($modules['column_right'] as $module){
    echo $module;
  }
?>
<? $this->endBlock();?>

  <!--Bottom block-->
<? $this->beginBlock('bottom'); ?>
<?
if(isset($modules['content_bottom']))
  foreach($modules['content_bottom'] as $module){
    echo $module;
  }
?>
<? $this->endBlock();?>


<?= \ibrarturi\scrollup\ScrollUp::widget([
  'theme' => 'image',
]); ?>

<? $js ="
function addToCart(id){
    $.post('". Url::toRoute(['cart/add']) ."', {'product_id' : id}, function(data){
      console.log(data);
    });
  }
";
$this->registerJs($js, View::POS_END)?>

advanced/frontend/views/category/found.php
<?
/* @var $sort  */
/* @var $provider  */
use yii\helpers\Html;
use yii\widgets\Menu;
use yii\widgets\ListView;
use yii\widgets\LinkSorter;
use frontend\components\DropSort;
use yii\widgets\ActiveForm;
use yii\web\View;
use yii\helpers\Url;

$query = yii\helpers\Html::encode($query);

$this->title = "Результаты поиска по запросу \"$query\"";
$this->params['breadcrumbs'][] = $this->title;

app\modules\search\SearchAssets::register($this);
$this->registerJs("jQuery('.search').highlight('{$query}');");

\yii\widgets\Pjax::begin();

echo \common\widgets\Alert::widget();

$form = ActiveForm::begin([
  'id'=> 'sorter-form',
  'options'=>[
    'data-pjax' => '1'
  ]
]);
?>

  <div class="display" data-toggle="buttons-radio">
    <span>Вид</span>
    <?=Html::Submitbutton('<i class="fa fa-th-large"></i>',
      [
        'name' => 'ProductForm[viewPage]',
        'value' => '_categoryGrid',
        'class' => $model->viewPage == '_categoryGrid' ? 'active' : ''
      ])
    ?>
    <?=Html::Submitbutton('<i class="fa fa-th-list"></i>',
      [
        'name' => 'CategoryForm[viewPage]',
        'value' => '_categoryList',
        'class' => $model->viewPage == '_categoryList' ? 'active' : ''
      ])
    ?>
  </div>

<?
echo DropSort::widget([
  'sort' => $sort,
  'attributes' => [
    'productName'=>[
      'label'=>'Имя'
    ],
    'price'=>[
      'label'=>'Цена'
    ],
  ],
  'options' =>[
    'class' => 'form-control',
    'id' => 'DDL',
    'onchange' => 'window.location = $("#DDL").val();',
  ],
  'DDL' =>[
    'labelSelect' => 'Сортировать по'
  ]
]);

echo $form->field($model, 'perPage')->dropDownList([
  '20'=>"20",
  '40'=>"40",
  '60'=>'60',
  '80'=>'80',
  '100'=>'100',
],
  [
    'id'=>'filterDrop',
    'onchange' => '$("#sorter-form").submit()'
  ]);
ActiveForm::end();
?>
<div class="search">
<?
echo ListView::widget([
  'dataProvider' => $provider,
  'itemView' => 'ListView/'. $model->viewPage,
  'layout' => '{items}{summary}{pager}',
  'pager' => [
    'options' => ['class' => 'bootstrap-styles pagination center-pag']
  ],
]);?>
</div>

<?\yii\widgets\Pjax::end();?>

  <!--Top block-->
<? $this->beginBlock('top'); ?>
<?
if(isset($modules['content_top']))
  foreach($modules['content_top'] as $module){
    echo $module;
  }
?>
<? $this->endBlock();?>

  <!--Left block-->
<? $this->beginBlock('left'); ?>
<?
if(isset($modules['column_left']))
  foreach($modules['column_left'] as $module){
    echo $module;
  }
?>
<? $this->endBlock();?>

  <!--Right block-->
<? $this->beginBlock('right'); ?>
<?
if(isset($modules['column_right']))
  foreach($modules['column_right'] as $module){
    echo $module;
  }
?>
<? $this->endBlock();?>

  <!--Bottom block-->
<? $this->beginBlock('bottom'); ?>
<?
if(isset($modules['content_bottom']))
  foreach($modules['content_bottom'] as $module){
    echo $module;
  }
?>
<? $this->endBlock();?>


<?= \ibrarturi\scrollup\ScrollUp::widget([
  'theme' => 'image',
]); ?>

<? $js ="
function addToCart(id){
    $.post('". Url::toRoute(['cart/add']) ."', {'product_id' : id}, function(data){
      console.log(data);
    });
  }
";
$this->registerJs($js, View::POS_END)?>

advanced/frontend/views/category/index.php
<?php
/* @var $this yii\web\View */
?>
<h1>category/index</h1>

<p>
    You may change the content of this page by modifying
    the file <code><?= __FILE__; ?></code>.
</p>

advanced/frontend/views/category/product.php
<?
/* @var array $attributes Атрибуты продукта  */
/* @var array $options Опции продукта  */
/* @var object $comment Модель комментариев  */

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use frontend\assets\FormstoneAsset;
use yii\web\View;
use common\widgets\Alert;
$this->title = $metaTags['title'];
//\yii\helpers\VarDumper::dump($metaTags, 10, 1 ); die;

foreach ($metaTags['meta'] as $name => $content) {
  $this->registerMetaTag([
    'name' => $name,
    'content' => $content
  ]);
}

FormstoneAsset::register($this);
$this->registerCssFile('@css/product.css');
$this->registerJsFile('//netdna.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js');

echo Alert::widget();
?>

<div id="prd-wrapper">
  <div class="product-left">
    <div class="prd-image">
      <div class="new-label">Новинка</div>
      <div class="main-img"><img src="../img/<?= $model->image ?>" alt="" width="370"></div>
    </div>
    <div id="color-but-wrapper">
      <div id="color-select">
        <span>Выберите цвет:</span>
        <ul>
          <li class="active"><img src="../img/colors/red.png" alt=""></li>
          <li><img src="../img/colors/green.png" alt=""></li>
          <li><img src="../img/colors/blue.png" alt=""></li>
          <li><img src="../img/colors/yellow.png" alt=""></li>
        </ul>
      </div>
      <div class="zoom"><img src="../img/zoom.png" alt=""></div>
      <div class="clear"></div>
      <div id="img-slider">
        <div class="slider-arrow"><img src="../img/slider-arrow-l.png" alt=""></div>
        <div><img src="../img/slider-item.jpg" alt=""></div>
        <div><img src="../img/slider-item.jpg" alt=""></div>
        <div><img src="../img/slider-item.jpg" alt=""></div>
        <div class="slider-arrow"><img src="../img/slider-arrow-r.png" alt=""></div>
      </div>
    </div>
  </div>
  <div class="product-right">
    <div id="prd-wrapper-right">
      <div class="prd-title"><?= $model->productName?></div>
      <div class="prd-sku">Артикул: <?= $model->model?></div>
      <div class="prd-color">Цвет: Слоновая кость</div>
      <div class="prd-short-txt">
        <?=$model->productDescription->short_description?>
      </div>
      <div id="attributes_short">
        <?
        foreach($attributes as $group => $attrs ){?>
          <div class="new-label grey"><?=$group?></div>
          <div class="prd-char-tbl">
            <?
            foreach ($attrs as  $attribute => $value ) {?>
              <div class="row">
                <div class="td"><?=$attribute?></div>
                <div class="td"><?=$value?></div>
              </div>
            <?}?>
          </div>
        <?}?>
      </div>
      <!--Опции-->
      <?$form = ActiveForm::begin([
        'id' => 'option-form',
        'action' => ['cart/add']
      ]);
      if(!empty($options)){?>
      <!--Рендерим доступные опции для товара-->
      <?=$this->render('_product-options', ['options' => $options, 'optionsForm' => $productForm, 'form' => $form]) ?>
      <?}?>

      <p id="tehnology">В товаре используется технология: <span class="important">SMART</span>
        Этот товар на <span class="important">Яндекс-маркете</span></p>

      <div class="share-btn">
        <img src="../img/social/share.png" alt="">
        <span>Поделиться</span>
      </div>
      <ul id="share-social">
        <li><img src="../img/social/fb.png" alt=""></li>
        <li><img src="../img/social/twitter.png" alt=""></li>
        <li><img src="../img/social/vk.png" alt=""></li>
        <li><img src="../img/social/rss.png" alt=""></li>
        <li><img src="../img/social/g+.png" alt=""></li>
      </ul>
      <div id="price-wrapper">
        <div class="prd-price">
          <?=number_format($model->price, 2, ',', ' ');?> грн
        </div>
        <?=Html::hiddenInput('product_id', $model->product_id);?>
        <?=Html::submitButton('Купить', ['class' => 'buy-btn'])?>
        <?$form->end()?>
      </div>
    </div>
  </div>
  <div class="clear"></div>

  <div class="tabbable"> <!-- Only required for left/right tabs -->
    <ul class="nav nav-tabs">
      <li class="active"><a href="#tab1" data-toggle="tab">Описание</a></li>
      <li><a href="#tab2" data-toggle="tab">Все характеристики</a></li>
      <li><a href="#comments" data-toggle="tab">Отзывы</a></li>
      <li><a href="#tab4" data-toggle="tab">Файлы/Документы</a></li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane fade active" id="tab1">
        <p class="desc">
          <?=$model->productDescription->description?>
        </p>
      </div>
      <div class="tab-pane fade" id="tab2">
        <div class="prd-char-tbl">
          <div class="row">
            <div class="td">Обьём плоскости для приготовления, п</div>
            <div class="td">5</div>
          </div>
          <div class="row">
            <div class="td">Приготовление под давлением</div>
            <div class="td">Да</div>
          </div>
          <div class="row">
            <div class="td">Приготовление на пару</div>
            <div class="td">Да</div>
          </div>
          <div class="row">
            <div class="td">Управление</div>
            <div class="td">Электронное</div>
          </div>
          <div class="row">
            <div class="td">Количество автоматических программ</div>
            <div class="td">11</div>
          </div>
          <div class="row">
            <div class="td">Количество уровней защиты</div>
            <div class="td">11</div>
          </div>
          <div class="row">
            <div class="td">Книга рецептов</div>
            <div class="td">Да</div>
          </div>
        </div>
      </div>
      <div class="tab-pane fade" id="comments">
        <?= \yii2mod\comments\widgets\Comment::widget([
          'model' => $comment,
        ]);
        ?>
      </div>
      <div class="tab-pane fade" id="tab4">
        <div class="attach-file">
          <img src="../img/file.png" alt="" align="left"> <span>Инструкция (16 mb)</span>
        </div>
        <br>
        <div class="attach-file">
          <img src="../img/file.png" alt="" align="left"> <span>Книга рецептов (4 mb)</span>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="clear"></div>

<!--Left block-->
<?php
$this->beginBlock('left');

$this->endBlock();
?>
<!--Right block-->
<?php $this->beginBlock('right'); ?>
<? $this->endBlock(); ?>

<!--Top block-->
<?php $this->beginBlock('top'); ?>
<? $this->endBlock(); ?>

<!--Bottom block-->
<? $this->beginBlock('bottom'); ?>
<?
if(isset($modules['content_bottom']))
  foreach($modules['content_bottom'] as $module){
    echo $module;
  }
?>
<? $this->endBlock();?>


<?= \ibrarturi\scrollup\ScrollUp::widget([
  'theme' => 'image',
]);
$formStone = <<<JS
$("input[type=checkbox], input[type=radio]").checkbox({customClass: "cust-check"});
$("input[type=number]").number({theme: "fs-light"});
JS;

$tabs = <<<JS
var url = document.location.toString();
if (url.match('#')) {
    $('.nav-tabs a[href="#' + url.split('#')[1] + '"]').click();
}

/*
// Change hash for page-reload
$('.nav-tabs a').on('shown.bs.tab', function (e) {
    window.location.hash = e.target.hash;
})*/

JS;


$this->registerJs($formStone, View::POS_END);
$this->registerJs($tabs, View::POS_END)?>